import React, { useEffect, useRef } from 'react';
import { FaCopy } from 'react-icons/fa';
import IconSparkles from '../Icon/IconSparkles';

export interface ChatMessage {
  content: string;
  isUser: boolean;
  createdAt?: string;
}

export interface ChatMessagesProps {
  messages: ChatMessage[];
  isLoading?: boolean;
}

function formatMessageTime(isoString?: string): string {
  if (!isoString) return '';
  try {
    const date = new Date(isoString);
    return date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });
  } catch {
    return '';
  }
}

const ChatMessages: React.FC<ChatMessagesProps> = ({ messages, isLoading = false }) => {
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, isLoading]);

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text).catch(() => {});
  };

  return (
    <div
      ref={scrollRef}
      className="flex-1 overflow-y-auto overflow-x-hidden p-3 space-y-3 bg-gray-50/50 dark:bg-dark/30 min-h-0 min-w-0 w-full"
    >
      {messages.map((msg, index) => (
        <div
          key={index}
          className={`flex min-w-0 ${msg.isUser ? 'justify-end' : 'justify-start'}`}
        >
          <div
            className={`max-w-[75%] rounded-2xl px-2 py-3 shadow-sm min-w-0 break-words ${
              msg.isUser
                ? 'bg-primary text-white rounded-br-md'
                : 'bg-white dark:bg-dark border border-white-light dark:border-dark text-gray-800 dark:text-gray-200 rounded-bl-md'
            }`}
          >
            {msg.isUser ? (
              <span className="text-sm break-words">{msg.content}</span>
            ) : (
              <>
                <div className="text-sm whitespace-pre-wrap break-words">{msg.content}</div>
                <div className="mt-2 pt-2 border-t border-white-light/50 dark:border-dark-light/50 flex items-center justify-between gap-2">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="flex items-center gap-1.5 text-xs text-gray-500 dark:text-gray-400">
                      <IconSparkles className="text-primary text-[10px] w-3 h-3" />
                      AI Assistant
                    </span>
                    {msg.createdAt && (
                      <span className="text-xs text-gray-400 dark:text-gray-500">
                        {formatMessageTime(msg.createdAt)}
                      </span>
                    )}
                    <button
                      type="button"
                      onClick={() => handleCopy(msg.content)}
                      className="p-1 rounded hover:bg-gray-100 dark:hover:bg-dark-light text-gray-500 dark:text-gray-400 hover:text-primary transition-colors"
                      title="Copy"
                      aria-label="Copy message"
                    >
                      <FaCopy className="w-3.5 h-3.5" />
                    </button>
                  </div>
                  <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300">  Generated by AI
</span>
                </div>
              </>
            )}
          </div>
        </div>
      ))}
      {isLoading && (
        <div className="flex justify-start min-w-0">
          <div className="max-w-[75%] rounded-2xl rounded-bl-md px-4 py-3 bg-white dark:bg-dark border border-white-light dark:border-dark shadow-sm w-fit min-w-0">
            <div className="flex items-center gap-2">
              <div
                className="animate-spin h-4 w-4 border-2 border-gray-400 dark:border-gray-500 border-t-transparent rounded-full shrink-0"
                aria-hidden
              />
              <span className="text-sm text-gray-600 dark:text-gray-400">AI is thinking...</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ChatMessages;
